### ISSUE TITLE
Cant close subtitle after choosing

### ISSUE THREAD

**Issue by rashid19961** [bbougot/Popcorn#169] opened 2017-12-22 15:26 UTC
Hi, This seems to be a bug, When i try to choose a subtitle inside a video that is playing and click close it doesnt let me close, i will have to force close the application and choose the subtitle language before clicking watch
![bug](https://user-images.githubusercontent.com/18513200/34303237-ed595cac-e74d-11e7-8bb2-f7274826bda7.png)

**Comment by harix786** [comment] 2017-12-22 17:58
Duplicate of #168

**Closed** 2017-12-22 21:43 UTC
