### ISSUE TITLE
Chromecast problem

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#59] opened 2017-05-17 16:21 UTC
Please, look this gif I made
https://gfycat.com/ScholarlyThoughtfulGangesdolphin

**Comment by bbougot** [comment] 2017-05-17 16:51
Same issue with release 2.0.8?

**Comment by Acme908** [comment] 2017-05-17 16:56
In 2.0.8:
http://i.imgur.com/65VstQp.png

**Comment by bbougot** [comment] 2017-05-19 09:19
I will investigate this soon

**Comment by theseraphim** [comment] 2017-07-31 04:06
Have you managed to solve this between V2.0.8 and current 2.4.5?

ill be at home in 2 hours ill try casting to my chromecast, if it fails ill attach visual studio debugger and work through the problem

**Comment by bbougot** [comment] 2017-07-31 08:04
The issue is still there. There is a problem with SharpCaster package which leads to, randomly, timeout for opening socket connexions to the Chromecast. I don't have much time to investigate more, but I think this issue (https://github.com/Tapanila/SharpCaster/issues/106) is related to it.

**Comment by bbougot** [comment] 2017-07-31 14:44
It should be better with v2.4.6 (e0bdb54)

**Comment by bbougot** [comment] 2017-08-16 09:53
Fixed in d65c627fd47bd4208d451f3914f7a8080daa2d95

**Closed by bbougot** 2017-08-16 09:53 UTC
Labels: bug, help wanted
