### ISSUE TITLE
An error has occured while trying to play the media.

### ISSUE THREAD

**Issue by Andis59** [bbougot/Popcorn#173] opened 2018-01-07 13:17 UTC
I'm trying to view the show Lewis, Season 9, I have tried all the episodes! It Buffers up to 100% and then I get an error:
**An error has occurred while trying to play the media.**

No logs are created!

What can be wrong and how do I fix this...

I'm using the latest 3.5.0 version. Other shows and movies works...

  EDIT: Using the latest code I have found where the exception throws and I have added a logging to the method EncounteredError in PlayerUserControl and I get this error

> 2018-01-09 15:55:18.2512|FATAL|Popcorn.UserControls.Player.PlayerUserControl|System.IO.FileNotFoundException: Unable to load minimum set of FFmpeg binaries from folder 'C:\Users\Anders\Documents\Visual%20Studio%202017\ProjectsVS2017\_Private\Popcorn\Popcorn\bin\x86\Debug\FFmpeg'. File 'avcodec-57.dll' is missing
>    at Unosquare.FFME.Core.Utils.RegisterFFmpeg(String overridePath)
>    at Unosquare.FFME.Commands.OpenCommand.ExecuteInternal()

The file avcodec-57.dll is in the FFmpeg directory and has File version: 57.107.100.0 and Product version: 3.4

Any ideas?

**Comment by bbougot** [comment] 2018-01-10 16:47
Please retry with the latest release (3.5.5)

**Comment by Andis59** [comment] 2018-01-10 18:01
I have now tried but I can't get it to work. Seems like it's an another problem...
This is what's happening:

Popcorn 3.5.5
Show: Lewis Series 9 episode 5

1	Buffering 100%
2	Black screen. When mouse over shows net traffic data. Download(316 kB/s), Upload (8 kB/s, Remaining time (00:22:00)
3	Still black screen. traffic data is all 0
4	Black screen "forever". If I click on the screen then it aborts with the same error as before: "An error has occured while trying to play the media,"

The file has been downloaded and is OK. I can copy it to some where and play it in VLC player.

I have made a change in Popcorn.exe.config so I get a log file. they are both attached.

[Popcorn.exe.config.txt](https://github.com/bbougot/Popcorn/files/1619907/Popcorn.exe.config.txt)
[logfile.log](https://github.com/bbougot/Popcorn/files/1619913/logfile.log)

**Comment by bbougot** [comment] 2018-01-12 18:54
Could you go to C:\Users\Anders\AppData\Local\Popcorn\app-3.5.6\FFmpeg
and tell me if you have all the following files:

* avcodec-57.dll
* avdevice-57.dll
* avfilter-6.dll
* avformat-57.dll
* avutil-55.dll
* postproc-54.dll
* swresample-2.dll
* swscale-4.dll

**Comment by Andis59** [comment] 2018-01-12 19:57
I have all of the files, see image
![ffmeg](https://user-images.githubusercontent.com/3873566/34892209-b117f0a0-f7d8-11e7-95d0-d934dc545249.png)

The download link on https://github.com/bbougot/Popcorn for the installer doesn't work! but I found it on https://github.com/bbougot/Popcorn/releases/

I tried to load the same Show and I got the same error as before!

Also I cloned the Popcorn project and it will not compile...
[popcorn356_compilerErrors.txt](https://github.com/bbougot/Popcorn/files/1627297/popcorn356_compilerErrors.txt)

**Comment by bbougot** [comment] 2018-01-12 20:28
I have fixed installer link.

This is weird, which OS are you using?

Regarding compilation, try to rebuild the solution

**Comment by Andis59** [comment] 2018-01-12 20:59
I'm using Windows 10 Home, 64-bits , Version 1709, OS Build 16299.192

Removed all bin and obj directories and the .vs and then the compilation works!

**Comment by bbougot** [comment] 2018-01-22 20:32
Could someone debug using Visual Studio and paste the Exception/Stacktrace..? I'm having trouble to solve this issue because it seems to differ from the OS/Config and I do not reproduce with my env.

**Comment by Andis59** [comment] 2018-02-12 12:07
Sorry for the long delay in updating this.

Somewhere in the latest update of Popcorn the loading of the FFmpeg starting to work!
Can't say exactly in which version this happend, but somewhere between 3.5.5 and 3.5.16 (which isn't much of a help...)

I think you can close this issue.

Thanks for a very very good application!
// Anders

**Comment by bbougot** [comment] 2018-02-13 14:42
Fixed in 3.6.0

**Closed by bbougot** 2018-02-13 14:42 UTC
Labels: bug, help wanted
